### Setup

```{r}
## --- Packages ------------------------------------ ##
library(multitaper)
library(pbapply)
library(kableExtra)
library(itsmr)
library(animation)
library(fields, quietly = TRUE, warn.conflicts = FALSE)
```

```{r}
## --- Splot + Spalette ---------------------------- ##
load("C:/Users/skyep/Documents/Research/Skyes_Toolbox/Splot.RData")
```

---

# Animations

## Frequency-Domain Animations

```{r}
## --- Choose your series
load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/UMP_c1_B150___mini.RData")
# load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/UMP_c1_B150___mini.RData")
```

```{r ani_prep}
## --- Plot Prep ---------------- ###

# Confidence Intervals (if it were Gaussian... isn't it more chi^2?)
bc1.low  <- pbc$bc1$mean - 2* pbc$bc1$se
bc1.high <- pbc$bc1$mean + 2* pbc$bc1$se
bc2.low  <- pbc$bc2$mean - 2* pbc$bc2$se
bc2.high <- pbc$bc2$mean + 2* pbc$bc2$se

# ylims
ylim.tx <- range(bc1.low, bc2.low, bc1.high, bc2.high, tru$xtf)
```

## Example: Stationary vs. UMP vs. Generalized Nonstationary

```{r}
# --- Data
load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/AR2_B200___mini.RData")
s.tru <- tru$xtf
load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/UMP_c1_B100___mini.RData")
u.tru <- tru$xtf
load("C:/Users/skyep/Documents/Research/PhD_Proposal/Data/other_B100___mini.RData")
n.tru <- tru$xtf
```

```{r}
# ---- Image Prep
wid <- 1800
skip <- 10

google <- "#CFC2B4"
```

```{r Example}

p <- 0
pb <- txtProgressBar(style = 3)

### --- Create GIF ------------------- ###

saveGIF({  for (my.t in seq(1,N,by = skip)) {
par(mfrow = c(1,3), mar = c(4.5,4.5,3.5,0), oma = c(0,0,0,2), bg = google)

##### (1)
  # --- True Plot
  splot(Fs, s.tru[my.t,],
        ylim = range(s.tru),
        type = "l", lwd = 2, colr = skrown$b1,labs = 0)
  
  # --- Labels
  slab(main = "Stationary", # UMP: c(t)*AR(2)",
       xlab = "Frequency",
       ylab = "Spectral Power")
  
  
  ## --- Legends (& other graphics) --------------------------- ##
  legend("topright", legend = bquote("Time t = "*.(p)*"  "),
         inset = c(0.05,0.08), cex = 1.2, bg = skrown$salt)
  
  
##### (2)
  # --- True Plot
  splot(Fs, u.tru[my.t,],
        ylim = range(u.tru),
        type = "l", lwd = 2, colr = skrown$b1,labs = 0)
  
  # --- Labels
  slab(main = "Uniformly Modulated", # UMP: c(t)*AR(2)",
       xlab = "Frequency")
  
  
  ## --- Legends (& other graphics) --------------------------- ##
  legend("topright", legend = bquote("Time t = "*.(p)*"  "),
         inset = c(0.05,0.08), cex = 1.2, bg = skrown$salt)
  
  
##### (3)
  # --- True Plot
  splot(Fs, n.tru[my.t,],
        ylim = range(n.tru),
        type = "l", lwd = 2, colr = skrown$b1,labs = 0)
  
  # --- Labels
  slab(main = "General Nonstationary", # UMP: c(t)*AR(2)",
       xlab = "Frequency")
  
  
  ## --- Legends (& other graphics) --------------------------- ##
  legend("topright", legend = bquote("Time t = "*.(p)*"  "),
         inset = c(0.05,0.08), cex = 1.2, bg = skrown$salt)
  
  
  
  
  # --- Progress
  p <- p+1
  setTxtProgressBar(pb, p/length(seq(1,N,by = skip)))

    } },
  
  # --- GIF details
  interval   = 0.01,
  movie.name = paste0("~/Research/CANSSI_23/Animations/example.gif"),
  ani.height = wid/3, ani.width = wid, ani.res = 180); gc()
```






















```{r f_domain_gif}

p <- 0
pb <- txtProgressBar(style = 3)

### --- Create GIF ------------------- ###

saveGIF({  for (my.t in seq(1,N,by = skip)) {
  
  # --- True Plot
  splot(Fs, tru$xtf[my.t,], type = "l", ylim = ylim.tx, lwd = 2, colr = skrown$smoke); gc()
  
  # --- Means
  lines(Fs, pbc$bc1$mean[my.t,], col = "dodgerblue2", lwd = 2) # OLD bc
  lines(Fs, pbc$bc2$mean[my.t,], col = "goldenrod"  , lwd = 2) # Cbc  
  
  # --- Standard Errors
  lines(Fs, bc1.low [my.t,] , col = skol$blue  , lwd = 1)
  lines(Fs, bc1.high[my.t,] , col = skol$blue  , lwd = 1)

  lines(Fs, bc2.low [my.t,], col = skol$orange, lwd = 1)
  lines(Fs, bc2.high[my.t,], col = skol$orange, lwd = 1)
  
  # --- Labels
  slab(main = "Spectrogram Estimates: example D", # UMP: c(t)*AR(2)",
       # subb = bquote(#"c(t) = exp{ (-t-500)"^2*"/(2(200"^2*")) }       "*
                     # "Blockwidth B ="~.(B)),
       xlab = "Frequency",
       ylab = bquote(hat(S)[X]~"(t = "*.(my.t)*", f)")); gc()
  
  
  ## --- Legends (& other graphics) --------------------------- ##
  legend("topright",
         legend = c("means",
                    #"mean +/- 2se","",
                    "True",
                    "1-BC",
                    "2-BC"),
         lty = c( 1, 
                  #1,NA,
                  1,NA,NA),
         lwd = c( 3, 
                  #1,NA,
                  NA,NA,NA),
         pch = c(NA,
                 #NA,NA,
                 19,19,19),
         
         col = c(skol$brown4, 
                 # skol$brown4, skol$brown4,
                 skol$brown4,"dodgerblue2","goldenrod"),
         bg  = "white",
         inset = c(0.01,0.02)
    )
  legend("topleft", legend = bquote("Time t ="*.(my.t)*"  "),
         inset = c(0.05,0.08), cex = 2.5,
         bg = if((my.t >= tb[1]) & (my.t <= max(tb))) {skastel$green} else {skastel$red})
  ## ---------------------------------------------------------- ##  
  
  gc()
    p <- p+1
    setTxtProgressBar(pb, p/length(seq(1,N,by = skip)))

    } },
  
  # --- GIF details
  interval   = 0.2,
  movie.name = paste0("~/Research/CANSSI_23/Animations/example.gif"),
  ani.height = wid/3, ani.width = wid); gc()
```